version: "3.8"
services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=
    volumes:
      - ./models_cache:/root/.cache/huggingface
    ports:
      - "8080:8000"
    command: >
      --model Qwen/Qwen2.5-1.8B-Instruct-AWQ
      --max-model-len 2048
      --gpu-memory-utilization 0.8
      --port 8000
      --api-key empty
      --disable-log-requests
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]